### ISSUE TITLE
module not available

### ISSUE THREAD

**Issue by bennypowers** [ng-milk/angular-animate-model-change#4]
I tried to add your code to my project, but was unable.

Steps to reproduce:

```
npm install -g yo gulp bower && npm install -g generator-gulp-angular
yo gulp-angular
bower install --save ng-animate-model-change
atom src/app/index.module.js //Add dm.animateModelChange
gulp serve
```

produces this error in console:

```
Uncaught Error: [$injector:modulerr] Failed to instantiate module kupatGivatHamivtar due to:
Error: [$injector:modulerr] Failed to instantiate module dm.animateModelChange due to:
Error: [$injector:nomod] Module 'dm.animateModelChange' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
http://errors.angularjs.org/1.3.0-build.3042+sha.76e57a7/$injector/nomod?p0=dm.animateModelChange
    at chrome-extension://ighdmehidhipcmcojjgiloacoafjmpfk/dist/hint.js:104:12
    at chrome-extension://ighdmehidhipcmcojjgiloacoafjmpfk/dist/hint.js:199:17
    at ensure (chrome-extension://ighdmehidhipcmcojjgiloacoafjmpfk/dist/hint.js:123:38)
    at module (chrome-extension://ighdmehidhipcmcojjgiloacoafjmpfk/dist/hint.js:197:14)
    at angular.module (chrome-extension://ighdmehidhipcmcojjgiloacoafjmpfk/dist/hint.js:1023:31)
    at angular.module (chrome-extension://ighdmehidhipcmcojjgiloacoafjmpfk/dist/hint.js:1173:38)
    at http://localhost:3000/bower_components/angular/angular.js:4447:22
    at forEach (http://localhost:3000/bower_components/angular/angular.js:341:20)
    at loadModules (http://localhost:3000/bower_components/angular/angular.js:4431:5)
    at http://localhost:3000/bower_components/angular/angular.js:4448:40
http://errors.angularjs.org/1.4.9/$injector/modulerr?p0=dm.animateModelChan…F%2Flocalhost%3A3000%2Fbower_components%2Fangular%2Fangular.js%3A4448%3A40
    at http://localhost:3000/bower_components/angular/angular.js:68:12
    at http://localhost:3000/bower_components/angular/angular.js:4470:15
    at forEach (http://localhost:3000/bower_components/angular/angular.js:341:20)
    at loadModules (http://localhost:3000/bower_components/angular/angular.js:4431:5)
    at http://localhost:3000/bower_components/angular/angular.js:4448:40
    at forEach (http://localhost:3000/bower_components/angular/angular.js:341:20)
    at loadModules (http://localhost:3000/bower_components/angular/angular.js:4431:5)
    at createInjector (http://localhost:3000/bower_components/angular/angular.js:4356:11)
    at doBootstrap (http://localhost:3000/bower_components/angular/angular.js:1677:20)
    at Object.angular.resumeBootstrap (http://localhost:3000/bower_components/angular/angular.js:1706:12)
http://errors.angularjs.org/1.4.9/$injector/modulerr?p0=kupatGivatHamivtar&…F%2Flocalhost%3A3000%2Fbower_components%2Fangular%2Fangular.js%3A1706%3A12)(anonymous function) @ angular.js:68(anonymous function) @ angular.js:4470forEach @ angular.js:341loadModules @ angular.js:4431createInjector @ angular.js:4356doBootstrap @ angular.js:1677angular.resumeBootstrap @ angular.js:1706maybeBootstrap @ hint.js:569
browser-sync-client.2.9.12.js:2 XHR finished loading: GET "http://localhost:3000/browser-sync/socket.io/?EIO=3&transport=polling&t=1458037264363-0".Request.create @ browser-sync-client.2.9.12.js:2Request @ browser-sync-client.2.9.12.js:2XHR.request @ browser-sync-client.2.9.12.js:2XHR.doPoll @ browser-sync-client.2.9.12.js:2Polling.poll @ browser-sync-client.2.9.12.js:2Polling.doOpen @ browser-sync-client.2.9.12.js:2Transport.open @ browser-sync-client.2.9.12.js:1Socket.open @ browser-sync-client.2.9.12.js:1Socket @ browser-sync-client.2.9.12.js:1Socket @ browser-sync-client.2.9.12.js:1Manager.open.Manager.connect @ browser-sync-client.2.9.12.js:1Manager @ browser-sync-client.2.9.12.js:1Manager @ browser-sync-client.2.9.12.js:1lookup @ browser-sync-client.2.9.12.js:1(anonymous function) @ browser-sync-client.2.9.12.js:9
```

Examining the output code shows that your ng-animate-model-change.js was never loaded.

**Comment by danmindru** [comment]
Hi @bennyp123, sorry for my uber-late reply, completely forgot about this one.
Did you get to the bottom of it?
Not a yeoman user myself, but I reckon it might be an issue with your setup.
It works ok in the [demo](https://github.com/ng-milk/angular-animate-model-change/blob/master/index.html#L251-L304). You might be missing a script tag or it might be loaded too late.
